server:
  port: 8080
spring:
  application:
    name: "loans"
  devtools:
    add-properties: false
  profiles:
    include: null
  datasource:
    url: "jdbc:postgresql://localhost:5432/makers_loans"
    username: "postgres"
    password: "admin"
    driverClassName: "org.postgresql.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
  data:
    redis:
      host: "localhost"
      port: 6379
  sql:
    init:
      data-locations: classpath:/data.sql
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
