DROP TABLE IF EXISTS loans;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
                       id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       role INT NOT NULL
);

CREATE TABLE loans (
                       id SERIAL PRIMARY KEY,
                       user_id INT NOT NULL,
                       amount DECIMAL(15,2) NOT NULL,
                       state INT NOT NULL,
                       payment_date VARCHAR(20) not null,
                       CONSTRAINT fk_loans_user FOREIGN KEY (user_id) REFERENCES users(id)
);

INSERT INTO users (id, email, "password", "role") VALUES (1, 'usuario@test.com', '123', 1);
INSERT INTO users (id, email, "password", "role") VALUES (2, 'admin@test.com', '123', 2);